graph TB
    Usuario -->|Interacción| UC1[Ingresar datos]

    UC1 --> UC5[Calcular corriente nominal Monofásico]
    UC1 --> UC6[Calcular corriente nominal Bifásico]
    UC1 --> UC7[Calcular corriente nominal Trifásico]
    UC1 --> UC8[Seleccionar interruptor termomagnético]
    UC1 --> UC9[Calcular capacidad de conducción]
    UC1 --> UC10[Calcular caída de tensión]
    UC1 --> UC11[Seleccionar conductor]
    UC1 --> UC12[Seleccionar canalización]
    UC1 --> UC2[Seleccionar tipo de carga]
    UC1 --> UC3[Mostrar información completa]
    UC1 --> UC4[Generar memoria de cálculo]
